theme = "tokyonight"

[editor]
cursor-shape.insert = "bar"
line-number = "relative"
bufferline = "multiple"
true-color = true
cursorline = true
color-modes = true
rulers = [80 , 120]
shell = ["fish", "-c"]

[editor.lsp]
display-messages = true

[editor.whitespace]
render = {tab = "all", space = "all"}

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[keys.normal]
"C-x" = ["collapse_selection", "keep_primary_selection"]
C-k = ["move_line_up", "scroll_up"]
C-j = ["move_line_down", "scroll_down"]
[keys.insert]
"C-x" = "normal_mode"
[keys.normal.space.space]
f = ":format"
c = ":insert-output bash ~/.config/helix/bin/insert_percent_cell.sh"
